name: EC2 SSH Test

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Create Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Debug (optional)
        run: |
          echo "HOST=${{ secrets.EC2_HOST }}"
          echo "USER=${{ secrets.EC2_USER }}"

      - name: SSH
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i private_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "hostname"
